export const MESSAGE_TYPES = {
  SAVE_WORD: "SAVE_WORD",
  DELETE_WORD: "DELETE_WORD",
  GET_WORDS: "GET_WORDS",
  GET_BOOKS: "GET_BOOKS",
  GET_BOOK_WORDS: "GET_BOOK_WORDS",
  EXPORT_WORDS: "EXPORT_WORDS",
  GET_SETTINGS: "GET_SETTINGS",
  SAVE_SETTINGS: "SAVE_SETTINGS",
  SYNC_NOW: "SYNC_NOW",
  TRIGGER_SYNC: "TRIGGER_SYNC",
  GET_SYNC_STATUS: "GET_SYNC_STATUS",
  AUTH_LOGIN: "AUTH_LOGIN",
  AUTH_REGISTER: "AUTH_REGISTER",
  AUTH_LOGOUT: "AUTH_LOGOUT",
  AUTH_STATUS: "AUTH_STATUS",
  TRANSLATE: "TRANSLATE",
  PING: "PING"
};

export function isKnownMessageType(type) {
  return Object.prototype.hasOwnProperty.call(MESSAGE_TYPES, type);
}
